Half grey columns variant #136
Netcentric/vg-macktrucks-com-rd pull request #205
Opened 2024-01-23 08:38 UTC by cogniSyb

Fix #136

Test URLs:
- Before: https://develop--vg-macktrucks-com-rd--netcentric.hlx.page/block-library/blocks/v2-columns
- After: https://136-columns-variant--vg-macktrucks-com-rd--netcentric.hlx.page/block-library/blocks/v2-columns

In context on a page:
- Before: https://develop--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/syb/diesel-powertrains
- After: https://136-columns-variant--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/syb/diesel-powertrains

The usage is the same as the regular V2 Column block. We add a modifier to the block (background-plane) for the gray background to appear. I’m open for suggestions of renaming this :)

2024-01-23 11:22 UTC, SantiagoHomps-NC approved these changes

2024-01-23 11:25 UTC, jonatan-lledo-netcentric commented on blocks/v2-columns/v2-columns.css
>  }
can you remove this max-width just for this variant to be applied from min-width: 744px. it looks odd from 512px to 743px IMHO

2024-01-23 11:28 UTC, jonatan-lledo-netcentric requested changes

2024-01-23 11:28 UTC, jonatan-lledo-netcentric commented on blocks/v2-columns/v2-columns.css
>  }
can you remove this max-width just for this variant to be applied from min-width: 744px. it looks odd from 560px to 743px IMHO
<img width="593" alt="Screenshot 2024-01-23 at 12 12 39" src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/117984204/94eb89da-41ec-4461-a4d5-41234de67203">
<img width="760" alt="Screenshot 2024-01-23 at 12 12 59" src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/117984204/2e03f43c-16b0-4fdb-9f1e-f19c99686023">

2024-01-26 13:38 UTC, jonatan-lledo-netcentric commented on blocks/v2-columns/v2-columns.css
>  }
then I approve it in a moment

2024-01-26 13:38 UTC, jonatan-lledo-netcentric approved these changes

2024-02-01 13:39 UTC, jonatan-lledo-netcentric approved these changes

2024-02-01 13:39 UTC, jonatan-lledo-netcentric commented on blocks/v2-columns/v2-columns.css
> +/* TODO: refactor generic section/block paddings */
nice TODO 😉

2024-02-06 14:39 UTC, merged