Media with content block
Netcentric/vg-macktrucks-com-rd pull request #210
Opened 2024-01-30 14:38 UTC by SantiagoHomps-NC

Fix #140 

Test URLs:
- Before: https://main--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/shomps/redesign/media-with-content
- After: https://140-media-content--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/shomps/redesign/media-with-content

2024-01-30 16:59 UTC, jonatan-lledo-netcentric approved these changes

2024-02-08 07:53 UTC, cogniSyb requested changes

2024-02-08 07:53 UTC, cogniSyb commented on blocks/v2-media-with-content/v2-media-with-content.css
> +  column-gap: 23px;
Should be rather 24px

2024-02-08 07:53 UTC, cogniSyb commented on blocks/v2-media-with-content/v2-media-with-content.css
> +.v2-media-with-content__content-wrapper.image-left {
Default state shouldn’t use a 'modifier' class. Remove `.image-left` from the selector

2024-02-08 07:53 UTC, cogniSyb commented on blocks/v2-media-with-content/v2-media-with-content.css
> +  .v2-media-with-content__content-wrapper.image-left {
Could this selector be simplified to `.v2-media-with-content__content-wrapper`?

2024-02-08 07:53 UTC, cogniSyb commented on blocks/v2-media-with-content/v2-media-with-content.css
> +.v2-media-with-content__content-wrapper.image-right {
BEM should be used, rewrite to `.v2-media-with-content__content-wrapper--image-right`

2024-02-08 07:53 UTC, cogniSyb commented on blocks/v2-media-with-content/v2-media-with-content.js
> +    contentWrapper.classList.add('image-right');
`${blockName}__content-wrapper--image-right`

2024-02-08 07:53 UTC, cogniSyb commented on blocks/v2-media-with-content/v2-media-with-content.js
> +  const hasImageLeft = (content[0].firstElementChild.tagName === 'PICTURE');
The image-left class is not necessary. This const could be removed, the following code to be changed to a ternary statement

2024-02-13 09:01 UTC, cogniSyb commented on blocks/v2-media-with-content/v2-media-with-content.css
> +  width: 100vw;
Add a max-width so that this image:
<img src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/133873665/3841aaea-4632-4fba-9805-4c4162bdf6a4" width="640">

doesn’t overlap 1440px as seen below:
<img src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/133873665/e918e396-7dcf-47fd-96f4-909b5f374be3" width="640">

2024-02-13 12:14 UTC, cogniSyb approved these changes

2024-02-13 13:25 UTC, jonatan-lledo-netcentric approved these changes

2024-02-13 13:36 UTC, merged