block done
Netcentric/vg-macktrucks-com-rd pull request #212
Opened 2024-02-05 10:59 UTC by SantiagoHomps-NC

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--vg-macktrucks-com-rd--netcentric.hlx.page/
- After: https://<branch>--vg-macktrucks-com-rd--netcentric.hlx.page/

2024-02-08 06:15 UTC, cogniSyb commented
We should give this block a different name. Something that describes what it does

2024-02-08 07:54 UTC, cogniSyb requested changes

2024-02-08 07:54 UTC, cogniSyb commented on blocks/v2-resources/v2-resources.css
> +@media (min-width: 768px) {
Project standard is to use 744px as breakpoint

2024-02-08 07:54 UTC, cogniSyb commented on blocks/v2-resources/v2-resources.js
> +      el.classList.add(`${blockName}__text`);
If `gap` is being used on the container instead of `margin` on this element, then the class on this element isn’t necessary

2024-02-08 07:54 UTC, cogniSyb commented on blocks/v2-resources/v2-resources.css
> +    width: 40vw;
A different unit is needed. In viewports beyond 1440px the text moves, which is not according to design.

2024-02-08 07:54 UTC, cogniSyb commented on blocks/v2-resources/v2-resources.css
> +  margin: 8px 0 16px;
Set `gap` together with `display: flex` on the parent, as done here: https://github.com/Netcentric/vg-macktrucks-com-rd/blob/main/blocks/v2-columns/v2-columns.css#L39

2024-02-08 09:26 UTC, cogniSyb commented on blocks/v2-resources/v2-resources.css
> +    left: 9%;
This doesn’t work well on high resolutions
<img src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/133873665/3f7c4593-13b5-4cff-a577-62be2bb119e9" width="600">

2024-02-08 09:27 UTC, SantiagoHomps-NC commented on blocks/v2-resources/v2-resources.css
> +@media (min-width: 768px) {
My bad... I was looking to non-redesign blocks

2024-02-08 10:58 UTC, SantiagoHomps-NC commented on blocks/v2-resources/v2-resources.css
> +  margin: 8px 0 16px;
But top and bottom margins are different... should I set gap: 8px and add 8px as margin in case I need to go up to 16px?

2024-02-08 11:00 UTC, SantiagoHomps-NC commented on blocks/v2-resources/v2-resources.css
> +    width: 40vw;
I think with `width: 40%` could be solved

2024-02-08 11:01 UTC, SantiagoHomps-NC commented on blocks/v2-resources/v2-resources.css
> +    left: 9%;
I changed the proposal, I think it looks better now.

2024-02-08 11:04 UTC, SantiagoHomps-NC commented on blocks/v2-resources/v2-resources.js
> +      el.classList.add(`${blockName}__text`);
ok, deleted

2024-02-12 15:51 UTC, jonatan-lledo-netcentric approved these changes

2024-02-15 17:34 UTC, cogniSyb approved these changes

2024-02-26 12:29 UTC, merged