DRAFT: v2 breadcrumbs v0.0.1
Netcentric/vg-macktrucks-com-rd pull request #213
Opened 2024-02-07 10:27 UTC by jonatan-lledo-netcentric

## New

the breadcrumb shows or hides based on the current width, even on resizing following the design pattern:
1st Home becomes an ellipsis
2nd current Active link is hided
3rd and beyond the middle links hide from the 2nd until the very last item

#
### Fix #44 

Test URLs:
- Before: https://main--vg-macktrucks-com-rd--netcentric.hlx.page/
- After: https://44-breadcrumbs--vg-macktrucks-com-rd--netcentric.hlx.page/

2024-02-07 18:39 UTC, cogniSyb requested changes
As per https://www.w3.org/WAI/ARIA/apg/patterns/breadcrumb/examples/breadcrumb/ I was expecting `<nav>` with `<ol>` and `<li>` to be used.

Clever solution, with the observers and calculations. Do I understand correctly that the demo with flexbox was not feasible for the requirements provided?

2024-02-07 18:39 UTC, cogniSyb commented on blocks/v2-breadcrumb/v2-breadcrumb.css
> +  outline: none;
The line `outline: none;` belongs to `.v2-breadcrumb__crumb:focus`

2024-02-07 18:39 UTC, cogniSyb commented on blocks/v2-breadcrumb/v2-breadcrumb.css
> +.v2-breadcrumb__crumb:focus,
Remove the selector for `:focus`. We only provide the focus style when the user interacts with a keyboard, via `:focus-visible`

2024-02-07 18:39 UTC, cogniSyb commented on blocks/v2-breadcrumb/v2-breadcrumb.css
> +  background-color: var(--c-secondary-graphite);
I agree that we should use the variables. Though now that I checked, I see that `#333` as color is defined for this

2024-02-07 18:39 UTC, cogniSyb commented on blocks/v2-breadcrumb/v2-breadcrumb.css
> +.v2-breadcrumb__crumb:not(.v2-breadcrumb__crumb--home)::before {
I’d rather see `::before` as part of an `<li>` so that it isn’t clickable.

The selector could be `.v2-breadcrumb__crumb + .v2-breadcrumb__crumb::before`, which is easier to read and more maintainable.

2024-02-07 18:39 UTC, cogniSyb commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +  ellipsis: '...',
Rather use a true ellipsis, which is one character. See https://practicaltypography.com/ellipses.html

2024-02-07 18:39 UTC, cogniSyb commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +  home: 'home',
Use `getTextLabel`, this content should be configurable in case of other languages

2024-02-07 18:39 UTC, cogniSyb commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +  const CheckCrumbsFits = () => {
This should be in camelCase: `checkCrumbsFits`

2024-02-07 18:39 UTC, cogniSyb commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +  block.setAttribute('aria-label', 'Breadcrumb');
Use `getTextLabel`, this content should be configurable in case of other languages

2024-02-07 18:39 UTC, cogniSyb commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +  const url = new URL(window.location.href);
As we’re not manipulating `window.location`, but rather reading contents of it, wouldn’t the following be easier?

```js
let hasPath = cfg && Object.hasOwn(cfg, 'path');
let url = hasPath ? cfg.path : window.location.pathname;
```

2024-02-07 18:39 UTC, cogniSyb commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +const removePathDash = (str) => str.replace(/-/g, ' ').toLowerCase();
Here you’re doing more than removing the dash from the path. You’re also transforming text to lowercase. So, could we rename it to `formatText`?

2024-02-07 18:39 UTC, cogniSyb commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +const areCrumbsFit = (block) => getCrumbsWidth(block) < getBlockWidth(block);
`areCrumbsFit` confused me a bit. I think `doCrumbsFit` or even `fitting` would be clearer

2024-02-07 18:39 UTC, cogniSyb commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +        crumb.textContent = crumb.dataset.content;
These two lines are easier if it’s written like this:
```js
if (index > 0) crumb.textContent = crumb.dataset.content;
```

2024-02-07 18:51 UTC, cogniSyb commented on blocks/v2-breadcrumb/v2-breadcrumb.css
> +  padding: 18px 16px 14px;
I think we should just do `padding: 16px` instead. At the 1200px breakpoint we should get rid of the horizontal padding, for alignment

2024-02-09 09:20 UTC, jonatan-lledo-netcentric commented on blocks/v2-breadcrumb/v2-breadcrumb.css
> +  padding: 18px 16px 14px;
done

2024-02-09 09:31 UTC, jonatan-lledo-netcentric commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +        crumb.textContent = crumb.dataset.content;
done

2024-02-09 09:32 UTC, jonatan-lledo-netcentric commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +const areCrumbsFit = (block) => getCrumbsWidth(block) < getBlockWidth(block);
I like fitting, so done

2024-02-09 09:32 UTC, jonatan-lledo-netcentric commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +const removePathDash = (str) => str.replace(/-/g, ' ').toLowerCase();
agree, done

2024-02-09 09:32 UTC, jonatan-lledo-netcentric commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +  const url = new URL(window.location.href);
is shorter and I like it, so done

2024-02-09 09:33 UTC, jonatan-lledo-netcentric commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +  block.setAttribute('aria-label', 'Breadcrumb');
placeholder updated. done

2024-02-09 09:34 UTC, jonatan-lledo-netcentric commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +  const CheckCrumbsFits = () => {
I missed it 😅, thanks. done

2024-02-09 09:34 UTC, jonatan-lledo-netcentric commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +  home: 'home',
done

2024-02-09 09:34 UTC, jonatan-lledo-netcentric commented on blocks/v2-breadcrumb/v2-breadcrumb.js
> +  ellipsis: '...',
I didn't know about a single character for this. done

2024-02-09 09:35 UTC, jonatan-lledo-netcentric commented on blocks/v2-breadcrumb/v2-breadcrumb.css
> +.v2-breadcrumb__crumb:not(.v2-breadcrumb__crumb--home)::before {
it works the same than the use of `:not()`, so done

2024-02-09 09:37 UTC, jonatan-lledo-netcentric commented on blocks/v2-breadcrumb/v2-breadcrumb.css
> +  background-color: var(--c-secondary-graphite);
I also checked it; this color doesn't yet have a proper variable. the other Figma file uses this color. updated

2024-02-09 09:37 UTC, jonatan-lledo-netcentric commented on blocks/v2-breadcrumb/v2-breadcrumb.css
> +.v2-breadcrumb__crumb:focus,
done

2024-02-09 09:37 UTC, jonatan-lledo-netcentric commented on blocks/v2-breadcrumb/v2-breadcrumb.css
> +  outline: none;
done

2024-02-09 09:40 UTC, jonatan-lledo-netcentric commented
> As per https://www.w3.org/WAI/ARIA/apg/patterns/breadcrumb/examples/breadcrumb/ I was expecting `<nav>` with `<ol>` and `<li>` to be used.

I added the nav and ul/li elements to follow the a11y pattern

> Clever solution, with the observers and calculations. Do I understand correctly that the demo with Flexbox was not feasible for the requirements provided?

the example removes all the elements from the end of the list and this doesn't work for our needs

2024-02-09 13:22 UTC, cogniSyb approved these changes

2024-02-12 09:20 UTC, SantiagoHomps-NC approved these changes

2024-02-15 17:29 UTC, merged