update fill & stroke functionallity in svgs
Netcentric/vg-macktrucks-com-rd pull request #61
Opened 2023-08-30 05:01 UTC by kesiah

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/tdziezyk/v2/
- After: https://adjust-icons--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/tdziezyk/v2/

2023-08-30 07:27 UTC, Lakshmishri requested changes
Can you check with your changes the speech icon and text for testimonial block looks misplaced. Probably missing height and width
![Screenshot 2023-08-30 at 09 26 24](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/4208604/e35cd03e-0754-4c75-9622-4c314a8b19d8)

2023-08-30 11:35 UTC, kesiah commented
> Can you check with your changes the speech icon and text for testimonial block looks misplaced. Probably missing height and width ![Screenshot 2023-08-30 at 09 26 24](https://user-images.githubusercontent.com/4208604/264263038-e35cd03e-0754-4c75-9622-4c314a8b19d8.png)

done!

2023-08-30 12:25 UTC, Lakshmishri approved these changes

2023-08-31 11:11 UTC, TomaszDziezykNetcentric approved these changes

2023-09-04 07:02 UTC, merged