tabbed carousel
Netcentric/vg-macktrucks-com-rd pull request #69
Opened 2023-09-05 09:30 UTC by kesiah

Fix #25

Test URLs:
- Before: https://main--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/laura/tabbed-carousel
- After: https://25-tabbed-carousel--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/laura/tabbed-carousel

2023-09-06 14:50 UTC, TomaszDziezykNetcentric requested changes

2023-09-06 14:50 UTC, TomaszDziezykNetcentric commented on blocks/v2-tabbed-carousel/v2-tabbed-carousel.js
> +          const { x: navigationX } = tabNavigation.getBoundingClientRect();
We have a very similar code in the `mouseover` handler. Can we move it to a separate function like:
```
const navigatioLineRestyle = (item, item2) => { // have no idea how to call the arguments better
        const { x: navigationX } = item2.getBoundingClientRect();
        const { x, width } = item.getBoundingClientRect();
        Object.assign(navigationLine.style, {
          left: `${x + tabNavigation.scrollLeft - navigationX}px`,
          width: `${width}px`,
        });
}

button.addEventListener('mouseover', (e) => {
        clearTimeout(timeout);
        navigatioLineRestyle(e.target, tabNavigation);
}

button.addEventListener('mouseout', (e) => {
    timeout = setTimout(() => {
              const activeItem = document.querySelector(`.${blockName}__navigation-item.active`);
        navigatioLineRestyle(activeItem, tabNavigation)
    });
}
```

2023-09-06 14:50 UTC, TomaszDziezykNetcentric commented on blocks/v2-tabbed-carousel/v2-tabbed-carousel.js
> +    const { x: navigationX } = navigation.getBoundingClientRect();
You reuse the function from the prev comment:
```
navigatioLineRestyle(activeNavigationItem, navigation)
```

2023-09-06 14:50 UTC, TomaszDziezykNetcentric commented on blocks/v2-tabbed-carousel/v2-tabbed-carousel.js
> +    const { x: navigationX } = navigation.getBoundingClientRect();
You reuse the function from the prev comment:
```
navigatioLineRestyle(activeNavigationItem, navigation)
```

2023-09-07 13:38 UTC, kesiah commented on blocks/v2-tabbed-carousel/v2-tabbed-carousel.css
> +  padding: 0;
Removed the styles, but then the spacings are not looking good when we add a text over the tabbed carousel. But that's not an issue of this block, so out of scope ;P

2023-09-14 10:35 UTC, markovukiceviccn approved these changes

2023-09-14 10:55 UTC, merged