35 specifications
Netcentric/vg-macktrucks-com-rd pull request #80
Opened 2023-09-19 15:53 UTC by kesiah

Fix #35

Test URLs:
- Before: https://main--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/laura/specs
- After: https://35-specifications--vg-macktrucks-com-rd--netcentric.hlx.page/drafts/laura/specs

2023-09-20 08:15 UTC, Lakshmishri requested changes

2023-09-20 08:15 UTC, Lakshmishri commented on blocks/v2-accordion/v2-accordion.css
> +.v2-accordion__item .v2-accordion__item:not(:last-child) {
I think this to avoid the grey border-bottom for  incase of nested accordion

2023-09-20 17:06 UTC, kesiah commented on blocks/v2-accordion/v2-accordion.css
> +.v2-accordion__item .v2-accordion__item:not(:last-child) {
You are right, because `.v2-accordion__item .v2-accordion__item:last-child` is removing the border bottom, that's why is not needed here.

2023-09-21 11:59 UTC, Lakshmishri approved these changes

2023-09-22 07:59 UTC, merged